import{a as L,i as a,S as w}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const E="44821264-a08a7741629af83990ada8b48",b="https://pixabay.com/api/";let c=1;const B=15,y=async e=>{try{const r=await L.get(b,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:c,per_page:B}});return c+=1,r.data}catch{throw new Error("Failed to fetch images")}},I=()=>{c=1},g=e=>{const r=document.getElementById("gallery");if(e.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=e.map(s=>`
      <a href="${s.largeImageURL}" class="gallery-item">
        <img src="${s.webformatURL}" alt="${s.tags}">
        <div>Likes: ${s.likes}</div>
        <div>Views: ${s.views}</div>
        <div>Comments: ${s.comments}</div>
        <div>Downloads: ${s.downloads}</div>
      </a>
    `).join("");r.insertAdjacentHTML("beforeend",n)},f=()=>{const e=document.querySelector(".loading");e.style.display="block"},h=()=>{const e=document.querySelector(".loading");e.style.display="none"},P=()=>{const e=document.getElementById("gallery");e.innerHTML=""},d=()=>{const e=document.getElementById("load-more");e.style.display="none"},S=()=>{const e=document.getElementById("load-more");e.style.display="block"};let u="",m=0,i=0,p=new w(".gallery a");const q=document.getElementById("search-form"),M=document.getElementById("load-more");q.addEventListener("submit",async e=>{e.preventDefault();const r=document.getElementById("search-input").value.trim();if(!r){a.warning({title:"Warning",message:"Search query cannot be empty!"});return}r!==u&&(u=r,I(),P(),d(),i=0),f();try{const n=await y(r);m=n.totalHits,i+=n.hits.length,g(n.hits),p.refresh(),v(),i>=m?(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),d()):S()}catch(n){a.error({title:"Error",message:n.message})}finally{h()}});M.addEventListener("click",async()=>{f();try{const e=await y(u);i+=e.hits.length,g(e.hits),p.refresh(),v(),i>=m&&(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),d())}catch(e){a.error({title:"Error",message:e.message})}finally{h()}});function v(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
